// Generated by WebUI. Do not edit.

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DemoShellRenderState {
    #[serde(rename = "apps")]
    pub apps: Vec<DemoShellRenderStateAppsItem>,
    #[serde(rename = "basePath")]
    pub base_path: String,
    #[serde(rename = "currentApp")]
    pub current_app: DemoShellRenderStateCurrentApp,
    #[serde(rename = "currentDisplay")]
    pub current_display: i64,
    #[serde(rename = "totalApps")]
    pub total_apps: i64,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DemoShellRenderStateAppsItem {
    #[serde(rename = "backend")]
    pub backend: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DemoShellRenderStateCurrentApp {
    #[serde(rename = "iframeUrl")]
    pub iframe_url: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug", default, skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "sourceUrl")]
    pub source_url: String,
}
