// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

use anyhow::{bail, Result};
use std::collections::BTreeSet;

use super::model::{PreferredType, TypeDefinition, TypeDocument, TypeRef};
use super::naming::to_pascal_case;
use super::writer::CodeWriter;
use super::LanguageGenerator;

pub(super) struct CSharpGenerator<'a> {
    namespace: &'a str,
    visibility: &'a str,
}

enum RenderTask<'a> {
    Type(&'a TypeRef),
    Text(&'static str),
}

impl<'a> CSharpGenerator<'a> {
    pub(super) fn new(namespace: &'a str, visibility: &'a str) -> Self {
        Self {
            namespace,
            visibility,
        }
    }
}

impl LanguageGenerator for CSharpGenerator<'_> {
    fn generate(&self, document: &TypeDocument) -> Result<String> {
        validate_namespace(self.namespace)?;

        let mut writer = CodeWriter::with_capacity(document.definitions.len() * 400);
        writer.line("// <auto-generated />");
        writer.line("#nullable enable");
        writer.blank_line();
        writer.push("namespace ");
        writer.push(self.namespace);
        writer.line(";");
        writer.blank_line();
        writer.line("#pragma warning disable SA1402 // File may only contain a single type");
        writer.blank_line();

        for definition in &document.definitions {
            render_class(&mut writer, definition, self.visibility)?;
            writer.blank_line();
        }

        let context_name = context_name(document);
        writer.line(
            "[global::System.Text.Json.Serialization.JsonSourceGenerationOptions(\
             DefaultIgnoreCondition = \
             global::System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]",
        );
        for root in &document.roots {
            writer.push("[global::System.Text.Json.Serialization.JsonSerializable(typeof(");
            writer.push(root);
            writer.line("))]");
        }
        writer.push(self.visibility);
        writer.push(" partial class ");
        writer.push(&context_name);
        writer.line(" : global::System.Text.Json.Serialization.JsonSerializerContext");
        writer.line("{");
        writer.line("}");
        Ok(writer.finish())
    }
}

fn render_class(
    writer: &mut CodeWriter,
    definition: &TypeDefinition,
    visibility: &str,
) -> Result<()> {
    writer.push(visibility);
    writer.push(" sealed class ");
    writer.line(&definition.name);
    writer.line("{");
    writer.indent();

    let mut names = BTreeSet::from([definition.name.clone()]);
    for (index, property) in definition.properties.iter().enumerate() {
        if index > 0 {
            writer.blank_line();
        }
        let property_name = allocate_property_name(&property.json_name, &mut names);
        let base_type = render_type(&property.ty);
        writer.push("[global::System.Text.Json.Serialization.JsonPropertyName(");
        writer.push(&serde_json::to_string(&property.json_name)?);
        writer.line(")]");
        writer.push("public ");
        writer.push(&property_type(&base_type, property.required));
        writer.push_char(' ');
        writer.push(&property_name);
        writer.push(" { get; init; }");
        if let Some(default) = property_default(&property.ty, property.required) {
            writer.push_char(' ');
            writer.push(default);
        }
        writer.newline();
    }

    writer.dedent();
    writer.line("}");
    Ok(())
}

fn allocate_property_name(json_name: &str, names: &mut BTreeSet<String>) -> String {
    let base = to_pascal_case(json_name);
    if names.insert(base.clone()) {
        return base;
    }

    let mut suffix = 2_u32;
    loop {
        let candidate = format!("{base}{suffix}");
        if names.insert(candidate.clone()) {
            return candidate;
        }
        suffix += 1;
    }
}

fn render_type(ty: &TypeRef) -> String {
    let mut output = String::new();
    let mut tasks = vec![RenderTask::Type(ty)];
    while let Some(task) = tasks.pop() {
        match task {
            RenderTask::Text(value) => output.push_str(value),
            RenderTask::Type(current) => match current {
                TypeRef::Any | TypeRef::Never | TypeRef::Null | TypeRef::Union(_) => {
                    output.push_str("global::System.Text.Json.JsonElement")
                }
                TypeRef::Boolean => output.push_str("bool"),
                TypeRef::Integer => output.push_str("long"),
                TypeRef::Number => output.push_str("double"),
                TypeRef::String => output.push_str("string"),
                TypeRef::Object(name) => output.push_str(name),
                TypeRef::Preferred { preferred, .. } => {
                    output.push_str(match preferred {
                        PreferredType::String => "string",
                        PreferredType::Boolean => "bool",
                        PreferredType::Number => "double",
                    });
                }
                TypeRef::Array(item) => {
                    tasks.push(RenderTask::Text(">"));
                    tasks.push(RenderTask::Type(item));
                    tasks.push(RenderTask::Text(
                        "global::System.Collections.Generic.IReadOnlyList<",
                    ));
                }
            },
        }
    }
    output
}

fn property_type(base: &str, required: bool) -> String {
    if required || base.ends_with('?') {
        base.to_string()
    } else {
        let mut nullable = String::with_capacity(base.len() + 1);
        nullable.push_str(base);
        nullable.push('?');
        nullable
    }
}

fn property_default(ty: &TypeRef, required: bool) -> Option<&'static str> {
    if !required {
        return None;
    }
    match ty {
        TypeRef::String => Some("= string.Empty;"),
        TypeRef::Preferred {
            preferred: PreferredType::String,
            ..
        } => Some("= string.Empty;"),
        TypeRef::Array(_) => Some("= [];"),
        TypeRef::Object(_) => Some("= new();"),
        _ => None,
    }
}

fn context_name(document: &TypeDocument) -> String {
    let base = format!("{}SerializationContext", document.name);
    if !document
        .definitions
        .iter()
        .any(|definition| definition.name == base)
    {
        return base;
    }

    let mut suffix = 2_u32;
    loop {
        let candidate = format!("{base}{suffix}");
        if !document
            .definitions
            .iter()
            .any(|definition| definition.name == candidate)
        {
            return candidate;
        }
        suffix += 1;
    }
}

fn validate_namespace(namespace: &str) -> Result<()> {
    if namespace.is_empty() {
        bail!("C# namespace cannot be empty");
    }
    for segment in namespace.split('.') {
        let mut bytes = segment.bytes();
        let Some(first) = bytes.next() else {
            bail!("C# namespace contains an empty segment");
        };
        if !(first.is_ascii_alphabetic() || first == b'_')
            || !bytes.all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
        {
            bail!("Invalid C# namespace segment '{segment}'");
        }
        if is_csharp_keyword(segment) {
            bail!("C# namespace segment '{segment}' is a reserved keyword");
        }
    }
    Ok(())
}

fn is_csharp_keyword(value: &str) -> bool {
    matches!(
        value,
        "abstract"
            | "as"
            | "base"
            | "bool"
            | "break"
            | "byte"
            | "case"
            | "catch"
            | "char"
            | "checked"
            | "class"
            | "const"
            | "continue"
            | "decimal"
            | "default"
            | "delegate"
            | "do"
            | "double"
            | "else"
            | "enum"
            | "event"
            | "explicit"
            | "extern"
            | "false"
            | "finally"
            | "fixed"
            | "float"
            | "for"
            | "foreach"
            | "goto"
            | "if"
            | "implicit"
            | "in"
            | "int"
            | "interface"
            | "internal"
            | "is"
            | "lock"
            | "long"
            | "namespace"
            | "new"
            | "null"
            | "object"
            | "operator"
            | "out"
            | "override"
            | "params"
            | "private"
            | "protected"
            | "public"
            | "readonly"
            | "ref"
            | "return"
            | "sbyte"
            | "sealed"
            | "short"
            | "sizeof"
            | "stackalloc"
            | "static"
            | "string"
            | "struct"
            | "switch"
            | "this"
            | "throw"
            | "true"
            | "try"
            | "typeof"
            | "uint"
            | "ulong"
            | "unchecked"
            | "unsafe"
            | "ushort"
            | "using"
            | "virtual"
            | "void"
            | "volatile"
            | "while"
    )
}
