// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

use anyhow::{bail, Result};
use std::collections::BTreeSet;

use super::model::{PreferredType, TypeDefinition, TypeDocument, TypeRef};
use super::naming::{is_rust_keyword, to_snake_case};
use super::writer::CodeWriter;
use super::LanguageGenerator;

pub(super) struct RustGenerator;

enum RenderTask<'a> {
    Type(&'a TypeRef),
    Text(&'static str),
}

impl LanguageGenerator for RustGenerator {
    fn generate(&self, document: &TypeDocument) -> Result<String> {
        if document.name == "Self"
            || document
                .definitions
                .iter()
                .any(|definition| definition.name == "Self")
        {
            bail!("Rust type name 'Self' is reserved; use --name to choose another root name");
        }

        let never_name = never_type_name(document);
        let mut writer = CodeWriter::with_capacity(document.definitions.len() * 320);
        writer.line("// Generated by WebUI. Do not edit.");
        writer.blank_line();

        if document.uses_never() {
            writer.line("#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]");
            writer.push("pub enum ");
            writer.push(&never_name);
            writer.line(" {}");
            writer.blank_line();
        }

        for definition in &document.definitions {
            render_struct(&mut writer, definition, &never_name)?;
            writer.blank_line();
        }

        if !document.routes.is_empty() {
            let variant_names = route_variant_names(document);
            writer.line("#[derive(Debug, Clone, serde::Serialize)]");
            writer.line("#[serde(untagged)]");
            writer.push("pub enum ");
            writer.push(&document.name);
            writer.line(" {");
            writer.indent();
            for (route, variant_name) in document.routes.iter().zip(variant_names) {
                writer.push(&variant_name);
                writer.push_char('(');
                writer.push(&route.type_name);
                writer.line("),");
            }
            writer.dedent();
            writer.line("}");
        }

        Ok(writer.finish())
    }
}

fn render_struct(
    writer: &mut CodeWriter,
    definition: &TypeDefinition,
    never_name: &str,
) -> Result<()> {
    writer.line("#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]");
    writer.push("pub struct ");
    writer.push(&definition.name);
    writer.line(" {");
    writer.indent();

    let mut names = BTreeSet::new();
    for property in &definition.properties {
        let field_name = allocate_field_name(&property.json_name, &mut names);
        writer.push("#[serde(rename = ");
        writer.push(&serde_json::to_string(&property.json_name)?);
        if property.required {
            writer.line(")]");
        } else {
            writer.line(", default, skip_serializing_if = \"Option::is_none\")]");
        }
        writer.push("pub ");
        writer.push(&field_name);
        writer.push(": ");
        if property.required {
            writer.push(&render_type(&property.ty, never_name));
        } else {
            writer.push("Option<");
            writer.push(&render_type(&property.ty, never_name));
            writer.push_char('>');
        }
        writer.line(",");
    }
    writer.dedent();
    writer.line("}");
    Ok(())
}

fn route_variant_names(document: &TypeDocument) -> Vec<String> {
    let mut used = BTreeSet::new();
    let mut names = Vec::with_capacity(document.routes.len());
    for route in &document.routes {
        let base = if route.variant_name == "Self" {
            "SelfRoute"
        } else {
            &route.variant_name
        };
        if used.insert(base.to_string()) {
            names.push(base.to_string());
            continue;
        }

        let mut suffix = 2_u32;
        loop {
            let candidate = format!("{base}{suffix}");
            if used.insert(candidate.clone()) {
                names.push(candidate);
                break;
            }
            suffix += 1;
        }
    }
    names
}

fn never_type_name(document: &TypeDocument) -> String {
    let mut used: BTreeSet<&str> = document
        .definitions
        .iter()
        .map(|definition| definition.name.as_str())
        .collect();
    used.insert(document.name.as_str());
    if !used.contains("WebUINever") {
        return "WebUINever".to_string();
    }

    let mut suffix = 2_u32;
    loop {
        let candidate = format!("WebUINever{suffix}");
        if !used.contains(candidate.as_str()) {
            return candidate;
        }
        suffix += 1;
    }
}

fn allocate_field_name(json_name: &str, names: &mut BTreeSet<String>) -> String {
    let mut base = to_snake_case(json_name);
    if is_rust_keyword(&base) {
        base.push('_');
    }
    if names.insert(base.clone()) {
        return base;
    }

    let mut suffix = 2_u32;
    loop {
        let candidate = format!("{base}_{suffix}");
        if names.insert(candidate.clone()) {
            return candidate;
        }
        suffix += 1;
    }
}

fn render_type(ty: &TypeRef, never_name: &str) -> String {
    let mut output = String::new();
    let mut tasks = vec![RenderTask::Type(ty)];
    while let Some(task) = tasks.pop() {
        match task {
            RenderTask::Text(value) => output.push_str(value),
            RenderTask::Type(current) => match current {
                TypeRef::Any | TypeRef::Union(_) => output.push_str("serde_json::Value"),
                TypeRef::Never => output.push_str(never_name),
                TypeRef::Null => output.push_str("()"),
                TypeRef::Boolean => output.push_str("bool"),
                TypeRef::Integer => output.push_str("i64"),
                TypeRef::Number => output.push_str("f64"),
                TypeRef::String => output.push_str("String"),
                TypeRef::Object(name) => output.push_str(name),
                TypeRef::Preferred { preferred, .. } => {
                    output.push_str(match preferred {
                        PreferredType::String => "String",
                        PreferredType::Boolean => "bool",
                        PreferredType::Number => "f64",
                    });
                }
                TypeRef::Array(item) => {
                    tasks.push(RenderTask::Text(">"));
                    tasks.push(RenderTask::Type(item));
                    tasks.push(RenderTask::Text("Vec<"));
                }
            },
        }
    }
    output
}
