// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

use anyhow::Result;

use super::model::{PreferredType, TypeDefinition, TypeDocument, TypeRef};
use super::naming::is_typescript_identifier;
use super::writer::CodeWriter;
use super::LanguageGenerator;

pub(super) struct TypeScriptGenerator;

enum RenderTask<'a> {
    Type(&'a TypeRef),
    Text(&'static str),
}

impl LanguageGenerator for TypeScriptGenerator {
    fn generate(&self, document: &TypeDocument) -> Result<String> {
        let mut writer = CodeWriter::with_indent(document.definitions.len() * 256, "  ");
        writer.line("// Generated by WebUI. Do not edit.");
        writer.blank_line();

        for definition in &document.definitions {
            render_interface(&mut writer, definition)?;
            writer.blank_line();
        }

        if !document.routes.is_empty() {
            writer.push("export type ");
            writer.push(&document.name);
            writer.line(" =");
            for (index, route) in document.routes.iter().enumerate() {
                writer.push("  | ");
                writer.push(&route.type_name);
                writer.line(if index + 1 == document.routes.len() {
                    ";"
                } else {
                    ""
                });
            }
            writer.blank_line();

            writer.push("export interface ");
            writer.push(&document.name);
            writer.line("ByPath {");
            writer.indent();
            for route in &document.routes {
                writer.push(&serde_json::to_string(&route.path)?);
                writer.push(": ");
                writer.push(&route.type_name);
                writer.line(";");
            }
            writer.dedent();
            writer.line("}");
            writer.blank_line();

            writer.push("export type ");
            writer.push(&document.name);
            writer.push("Path = keyof ");
            writer.push(&document.name);
            writer.line("ByPath;");
            writer.blank_line();
            writer.push("export type ");
            writer.push(&document.name);
            writer.push("For<Path extends ");
            writer.push(&document.name);
            writer.push("Path> = ");
            writer.push(&document.name);
            writer.line("ByPath[Path];");
        }

        Ok(writer.finish())
    }
}

fn render_interface(writer: &mut CodeWriter, definition: &TypeDefinition) -> Result<()> {
    writer.push("export interface ");
    writer.push(&definition.name);
    writer.line(" {");
    writer.indent();
    for property in &definition.properties {
        if is_typescript_identifier(&property.json_name) {
            writer.push(&property.json_name);
        } else {
            writer.push(&serde_json::to_string(&property.json_name)?);
        }
        if !property.required {
            writer.push_char('?');
        }
        writer.push(": ");
        writer.push(&render_type(&property.ty));
        writer.line(";");
    }
    writer.dedent();
    writer.line("}");
    Ok(())
}

fn render_type(ty: &TypeRef) -> String {
    let mut output = String::new();
    let mut tasks = vec![RenderTask::Type(ty)];
    while let Some(task) = tasks.pop() {
        match task {
            RenderTask::Text(value) => output.push_str(value),
            RenderTask::Type(current) => match current {
                TypeRef::Any => output.push_str("unknown"),
                TypeRef::Never => output.push_str("never"),
                TypeRef::Null => output.push_str("null"),
                TypeRef::Boolean => output.push_str("boolean"),
                TypeRef::Integer | TypeRef::Number => output.push_str("number"),
                TypeRef::String => output.push_str("string"),
                TypeRef::Object(name) => output.push_str(name),
                TypeRef::Preferred { preferred, .. } => {
                    output.push_str(match preferred {
                        PreferredType::String => "string",
                        PreferredType::Boolean => "boolean",
                        PreferredType::Number => "number",
                    });
                }
                TypeRef::Array(item) => {
                    tasks.push(RenderTask::Text(">"));
                    tasks.push(RenderTask::Type(item));
                    tasks.push(RenderTask::Text("Array<"));
                }
                TypeRef::Union(branches) => {
                    for (index, branch) in branches.iter().enumerate().rev() {
                        tasks.push(RenderTask::Type(branch));
                        if index > 0 {
                            tasks.push(RenderTask::Text(" | "));
                        }
                    }
                }
            },
        }
    }
    output
}
