// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

use anyhow::{bail, Context, Result};
use clap::{Args, ValueEnum};
use expand_tilde::expand_tilde;
use serde_json::Value;
use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;

#[derive(Args)]
pub struct StateTypesArgs {
    /// Path to a JSON Schema file produced by `webui state-schema`
    pub file: PathBuf,

    /// Language to generate
    #[arg(long, value_enum, default_value_t = StateTypesLanguage::Csharp)]
    pub lang: StateTypesLanguage,

    /// C# namespace for generated types
    #[arg(long, default_value = "WebUI.Generated")]
    pub namespace: String,

    /// Root C# class name. Defaults to the schema title.
    #[arg(long)]
    pub class_name: Option<String>,
}

#[derive(Clone, Copy, ValueEnum)]
pub enum StateTypesLanguage {
    Csharp,
}

pub fn execute(args: &StateTypesArgs) -> Result<()> {
    let input_file = expand_tilde(&args.file)
        .with_context(|| format!("Failed to expand input path: {}", args.file.display()))?
        .into_owned();
    let schema_text = fs::read_to_string(&input_file)
        .with_context(|| format!("Failed to read schema {}", input_file.display()))?;
    let schema: Value = serde_json::from_str(&schema_text)
        .with_context(|| format!("Failed to parse schema {}", input_file.display()))?;

    match args.lang {
        StateTypesLanguage::Csharp => {
            let class_name = args
                .class_name
                .clone()
                .map(|name| to_pascal_case(&name))
                .or_else(|| schema.get("title").and_then(Value::as_str).map(to_pascal_case))
                .unwrap_or_else(|| "WebUIState".to_string());
            println!("{}", generate_csharp(&schema, &args.namespace, &class_name)?);
        }
    }

    Ok(())
}

fn generate_csharp(schema: &Value, namespace: &str, root_class_name: &str) -> Result<String> {
    let mut classes = Vec::new();
    collect_csharp_class(root_class_name, schema, &mut classes)?;

    let mut output = String::new();
    output.push_str("// <auto-generated />\n");
    output.push_str("namespace ");
    output.push_str(namespace);
    output.push_str(";\n\n");
    output.push_str("using System.Collections.Generic;\n");
    output.push_str("using System.Text.Json.Serialization;\n\n");
    output.push_str("#pragma warning disable SA1402 // File may only contain a single type\n\n");

    for class in classes {
        output.push_str(&class);
        output.push('\n');
    }

    output.push_str("[JsonSourceGenerationOptions(DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault, PropertyNameCaseInsensitive = true)]\n");
    output.push_str("[JsonSerializable(typeof(");
    output.push_str(root_class_name);
    output.push_str("))]\n");
    output.push_str("internal partial class ");
    output.push_str(root_class_name);
    output.push_str("SerializationContext : JsonSerializerContext\n{\n}\n");

    Ok(output)
}

fn collect_csharp_class(class_name: &str, schema: &Value, classes: &mut Vec<String>) -> Result<()> {
    let properties = schema
        .get("properties")
        .and_then(Value::as_object)
        .ok_or_else(|| anyhow::anyhow!("Schema object {class_name} has no properties"))?;

    let mut nested_classes = Vec::new();
    let mut class_output = String::new();
    class_output.push_str("internal sealed class ");
    class_output.push_str(class_name);
    class_output.push_str("\n{\n");

    let ordered_properties: BTreeMap<_, _> = properties.iter().collect();
    for (json_name, property_schema) in ordered_properties {
        let property_name = to_pascal_case(json_name);
        let property_type = csharp_type_for_property(class_name, &property_name, property_schema, &mut nested_classes)?;
        class_output.push_str("    [JsonPropertyName(\"");
        class_output.push_str(json_name);
        class_output.push_str("\")]\n");
        class_output.push_str("    public ");
        class_output.push_str(&property_type);
        class_output.push(' ');
        class_output.push_str(&property_name);
        class_output.push_str(" { get; init; }");
        let default_value = csharp_default_value(&property_type);
        if !default_value.is_empty() {
            class_output.push(' ');
            class_output.push_str(default_value);
        }
        class_output.push_str("\n\n");
    }

    if class_output.ends_with("\n\n") {
        class_output.truncate(class_output.len() - 1);
    }
    class_output.push_str("}\n");
    classes.push(class_output);

    for (nested_name, nested_schema) in nested_classes {
        collect_csharp_class(&nested_name, &nested_schema, classes)?;
    }

    Ok(())
}

fn csharp_type_for_property(
    parent_class_name: &str,
    property_name: &str,
    schema: &Value,
    nested_classes: &mut Vec<(String, Value)>,
) -> Result<String> {
    match schema.get("type").and_then(Value::as_str) {
        Some("boolean") => Ok("bool".to_string()),
        Some("number") => Ok("double".to_string()),
        Some("integer") => Ok("int".to_string()),
        Some("string") => Ok("string".to_string()),
        Some("array") => {
            let item_schema = schema
                .get("items")
                .ok_or_else(|| anyhow::anyhow!("Array property {property_name} has no items schema"))?;
            if item_schema.get("type").and_then(Value::as_str) == Some("object") {
                let nested_name = format!("{parent_class_name}{property_name}Item");
                nested_classes.push((nested_name.clone(), item_schema.clone()));
                Ok(format!("IReadOnlyList<{nested_name}>"))
            } else {
                let item_type = csharp_type_for_property(parent_class_name, property_name, item_schema, nested_classes)?;
                Ok(format!("IReadOnlyList<{item_type}>"))
            }
        }
        Some("object") => {
            let nested_name = format!("{parent_class_name}{property_name}");
            nested_classes.push((nested_name.clone(), schema.clone()));
            Ok(nested_name)
        }
        Some(other) => bail!("Unsupported JSON Schema type {other} for {property_name}"),
        None => Ok("string".to_string()),
    }
}

fn csharp_default_value(property_type: &str) -> &'static str {
    if property_type == "string" {
        "= string.Empty;"
    } else if property_type.starts_with("IReadOnlyList<") {
        "= [];"
    } else if property_type == "bool" || property_type == "double" || property_type == "int" {
        ""
    } else {
        "= new();"
    }
}

fn to_pascal_case(value: &str) -> String {
    let mut output = String::new();
    let mut uppercase_next = true;
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            if uppercase_next {
                output.push(ch.to_ascii_uppercase());
                uppercase_next = false;
            } else {
                output.push(ch);
            }
        } else {
            uppercase_next = true;
        }
    }

    if output.is_empty() {
        "Value".to_string()
    } else if output.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        format!("Value{output}")
    } else {
        output
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn generate_csharp_outputs_nested_list_types() {
        let schema = json!({
            "title": "FilesRenderState",
            "type": "object",
            "properties": {
                "filesList": {
                    "type": "object",
                    "properties": {
                        "items": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "name": { "type": "string" },
                                    "shared": { "type": "boolean" }
                                }
                            }
                        }
                    }
                }
            }
        });

        let output = generate_csharp(&schema, "Demo", "FilesRenderState").unwrap();
        assert!(output.contains("internal sealed class FilesRenderState"));
        assert!(output.contains("public FilesRenderStateFilesList FilesList { get; init; } = new();"));
        assert!(output.contains("public IReadOnlyList<FilesRenderStateFilesListItemsItem> Items { get; init; } = [];"));
        assert!(output.contains("public bool Shared { get; init; }"));
        assert!(output.contains("internal partial class FilesRenderStateSerializationContext : JsonSerializerContext"));
    }
}
