// Generated by WebUI. Do not edit.

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct RustExampleState {
    #[serde(rename = "details")]
    pub details: String,
    #[serde(rename = "items")]
    pub items: Vec<RustExampleStateItemsItem>,
    #[serde(
        rename = "showDetails",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub show_details: Option<bool>,
    #[serde(rename = "title")]
    pub title: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct RustExampleStateItemsItem {
    #[serde(rename = "label")]
    pub label: String,
}
